# Generated by Django 4.2.18 on 2025-01-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_alter_recommendation_uploaded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='duration',
        ),
    ]
