# Generated by Django 4.2.19 on 2025-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_remove_playlistsong_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
